#pragma once

enum
{
	SOCKS5_NO_AUTHENTICATION_REQUIRED = 0x00,
	SOCKS5_GSSAPI = 0x01,
	SOCKS5_AUTHENTICATION_REQUIRED = 0x02,
	SOCKS5_NO_ACCEPTABLE_METHODS = 0xFF
};

enum
{
	SOCKS5_CMD_CONNECT = 0x01,
	SOCKS5_CMD_BIND = 0x02,
	SOCKS5_CMD_UDP_ASSOCIATE = 0x03
};

enum
{
	SOCKS5_ADDR_TYPE_IPV4 = 0x01,
	SOCKS5_ADDR_TYPE_DOMAIN_NAME = 0x03,
	SOCKS5_ADDR_TYPE_IPV6 = 0x04
};

enum
{
	SOCKS5_REPLY_SUCCEEDED = 0,
	SOCKS5_REPLY_GENERAL_FAILURE = 1,
	SOCKS5_REPLY_CONNECTION_NOT_ALLOWED_BY_RULESET = 2,
	SOCKS5_REPLY_NETWORK_UNREACHABLE = 3,
	SOCKS5_REPLY_HOST_UNREACHABLE = 4,
	SOCKS5_REPLY_CONNECTION_REFUSED = 5,
	SOCKS5_REPLY_TTL_EXPIRED = 6,
	SOCKS5_REPLY_COMMAND_NOT_SUPPORTED = 7,
	SOCKS5_REPLY_ADDRESS_TYPE_NOT_SUPPORTED = 8,
};